
const ITEM_SALE_START_PRICE = 100 
const PAYMENT_MEANS_DEF = 'USDT'
const PAYMENT_ADDRESS_DEF = ''
const PRICE_HIKE_PERCENT = 20 
module.exports={
	ITEM_SALE_START_PRICE 
	, PAYMENT_MEANS_DEF
	, PAYMENT_ADDRESS_DEF
	, PRICE_HIKE_PERCENT 
}
